---

- name: check configuration is valid 
  ansible.builtin.assert:
    that:
      - restic_repo is match("s3:https:\/\/.*")
      - (restic_s3_access_key | string | length) >= 20
      - (restic_s3_secret_key | string | length) >= 5

- name: add harpocrates user
  ansible.builtin.user:
    name: harpocrates
    shell: /bin/bash # /usr/sbin/nologin
    home: /home/harpocrates
    skeleton: yes # populate basic shit in $HOME
    password: "{{ restic_pass | string | password_hash('sha512', 65534 | random(seed=group_names[0]) | string) }}"
    system: yes

- ansible.builtin.import_tasks: restic.yml

- ansible.builtin.import_tasks: cron.yml

- name: get repository status
  run_once: yes
  become_user: harpocrates
  ansible.builtin.shell: "eval export `crontab -l`; /usr/bin/restic --no-cache snapshots"
  register: repository_status
  changed_when: repository_status.rc != 0
  notify: initialize repository
  failed_when: no
